minVersion: 0.23.1
github:
  owner: getsentry
  repo: sentry-php-agent
changelogPolicy: simple
statusProvider:
  name: github
artifactProvider:
  name: none
targets:
  - name: github
  - name: registry
    type: sdk
    config:
      canonical: 'composer:sentry/sentry-agent'
