name: PHAR

on:
  pull_request:
  push:
    branches:
      - main
      
concurrency: 
  group: ${{ github.workflow }}-${{ github.head_ref }}

jobs:
  build-agent:
    name: Build Agent
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}
        
      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401
        with:
          php-version: '7.2'
          tools: composer:v2, box
          ini-values: phar.readonly=0

      - name: Install dependencies
        working-directory: agent
        run: composer update --no-progress --no-interaction --prefer-dist
        
      - name: Build PHAR
        run: scripts/build.sh

      - name: Test PHAR
        run: php bin/sentry-agent help
      