name: Build PHAR

on:
  pull_request:

permissions:
  contents: read

jobs:
  build-agent:
    name: Build Agent
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref || github.ref }}
        
      - name: Setup PHP for agent dependencies
        uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # v2.35.4
        with:
          php-version: '7.2'
          tools: composer:v2

      - name: Install dependencies
        working-directory: agent
        run: composer update --no-progress --no-interaction --prefer-dist

      - name: Setup PHP for Box
        uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # v2.35.4
        with:
          php-version: '8.4'
          tools: box
          ini-values: phar.readonly=0
        
      - name: Build PHAR
        run: scripts/build.sh

      - name: Setup PHP for PHAR test
        uses: shivammathur/setup-php@ec406be512d7077f68eed36e63f4d91bc006edc4 # v2.35.4
        with:
          php-version: '7.2'

      - name: Test PHAR
        run: php bin/sentry-agent help

      - name: Commit PHAR
        uses: EndBug/add-and-commit@a94899bca583c204427a224a7af87c02f9b325d5 # v9.1.4
        with:
          add: "bin/sentry-agent bin/sentry-agent.sig"
          message: "Add PHAR artifact"
          default_author: github_actions
