name: PHPStan

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@9e72090525849c5e82e596468b86eb55e9cc5401 # pin@2.32.0
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer update --no-progress --no-interaction --prefer-dist

      - name: Run script
        run: vendor/bin/phpstan analyse
